
struct STRUCT_NAME {
	STRUCT_FIELDS
	STRUCT_NAME():FIELD_INITIALIZERS{}
};
RECORD_TYPE RECORD_NAME;

EXTERNFREE_LIST_NAME<STRUCT_NAME> FREE_LIST_INSTANCE_COLD;
EXTERNFREE_LIST_NAME<RECORD_NAME> FREE_LIST_INSTANCE_HOT;

