
struct STRUCT_NAME {
	STRUCT_FIELDS
	STRUCT_NAME()FIELD_INITIALIZERS{}
};

EXTERNFREE_LIST_NAME<STRUCT_NAME, SIZE_COLD> FREE_LIST_INSTANCE_COLD;
RECORD_TYPE RECORD_NAME;
EXTERNFREE_LIST_NAME<RECORD_NAME, SIZE_HOT> FREE_LIST_INSTANCE_HOT;

