

char BYTE_DATA_HOT[SIZE_HOT];
char BYTE_DATA_COLD[SIZE_COLD];
FREE_LIST_NAME<RECORD_NAME> FREE_LIST_INSTANCE_HOT(BYTE_DATA_HOT, BYTE_DATA_HOT+SIZE_HOT, HOT_ALIGNMENT);
FREE_LIST_NAME<STRUCT_NAME> FREE_LIST_INSTANCE_COLD(BYTE_DATA_COLD, BYTE_DATA_COLD+SIZE_COLD, COLD_ALIGNMENT);
